FROM mhart/alpine-node:8.0.0

RUN apk add --no-cache git make gcc g++ python libtool autoconf automake \
    && npm install pm2 -g

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD package.json ./
RUN npm install \
    && apk del make gcc g++ python libtool autoconf automake

ADD . /usr/src/app

EXPOSE 2000 2001 2002 2003

CMD ["pm2", "start", "API.json", "--no-daemon"]
